### ISSUE TITLE
NPE if user has configured an invalid email in git

### ISSUE THREAD

**Issue by wolverian** [jenkinsci/flowdock-plugin#20]
Given a commit with author `foo <@>`, the Flowdock plugin crashes when gathering author info for the message:

```
FATAL: 0
java.lang.ArrayIndexOutOfBoundsException: 0
    at hudson.plugins.git.GitChangeSet.findOrCreateUser(GitChangeSet.java:291)
    at hudson.plugins.git.GitChangeSet.getAuthor(GitChangeSet.java:349)
    at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:350)
    at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:346)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:672)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
```

**Comment by wolverian** [comment]
Hm, looks like this might be the git plugin's fault after all.

**Comment by arcivanov** [comment]
@wolverian nothing to do with Flowdock - look a stack trace.

**Comment by wolverian** [comment]
Yep, thanks and sorry for the noise.
